title: 迈克.顿的技术博客
email: 894733082@qq.com
description: > # this means to ignore newlines until "baseurl:"
  使用 jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mikedeng.github.io" # the base hostname & protocol for your site
twitter_username: mikedeng
github_username:  mikedeng

# Build settings
markdown: kramdown

gems: 
  - jekyll-paginate

paginate: 8
paginate_path: "/:num"